# NumPy & SciPy

## Things you will learn in this workshop <br>
- Introduction to Numpy and Scipy packages <br>
- Import data <br>
- Create and manipulate multidimensional Numpy arrays <br>
- Do linear algebra in Python <br>
- Use SciPy’s basic statistical functions <br>
- Use array operations to speed up your calculations <br>

# Reproducibility

In [ ]:
Which Python version am I using ?

In [1]:
import sys
print(sys.version)

3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]


In [2]:
import numpy as np # Numpy package

My Numpy version is 1.14.5, how do we get it ?

In [23]:
print(np.__version__)

1.14.5


# Computing in Python

Scientific computing in Python builds upon a small core of packages:


NumPy, the fundamental package for numerical computation. It defines the numerical array and matrix types and basic operations on them.

The SciPy library, a collection of numerical algorithms and domain-specific toolboxes, including signal processing, optimization, statistics and much more.

# Numpy (Numerical Python)

-> a powerful N-dimensional array object <br>
-> tools for integrating C/C++ and Fortran code <br>
-> sophisticated (broadcasting) functions <br>
-> useful linear algebra, Fourier transform, and random number capabilities <br>


Before we understand these statements from Numpy page we will go to the basic data storage in Pyhton (Data structures)
Four built-in data structures in Python - list, tuple, dictionary and set
Arrays is like lists but a lot different from lists which we will see 


List:
    
    A list is a data structure that holds an ordered collection of items.
    List is a most versatile datatype which can be written as a list of items(comma sep values) between square brackets.
    Important thing about a list is that items in a list need not be of the same type.

Numpy provides many functions to create arrays
Numpy offers several ways to index into arrays.
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

The basic type: ndarray
The n-dimensional array (ndarray) is the fundamental data structure in NumPy. It is a table of elements, all of the same type, which can be indexed (that is, accessed) by a tuple of integers

- NumPy array is a central data structure of the numpy library.<br>
- NumPy’s main object is the homogeneous multidimensional array. <br>
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.<br>
- In NumPy dimensions are called axes.<br>
- NumPy’s array class is called "ndarray"<br>
- The number of dimensions is the rank of the array;<br>
- The shape of an array is a tuple of integers giving the size of the array along each dimension.<br>

Datatypes:
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [17]:
list1=[1,2,3,4,5]
list2=["gene1","gene2","gene3","gene4"] # can hold different types of data # Add or remove the data

# Accessing Values in Lists

In [18]:
print("My first value in list1 is :",list1[0]) # does strat from 0

My first value in list1 is : 1


In [19]:
print("My first value in list2 is :",list2[0])

My first value in list2 is : gene1


In [20]:
#add any values using built in function "append"
#Add an item to the end of the list
list2.append('gene5')

In [21]:
list2

['gene1', 'gene2', 'gene3', 'gene4', 'gene5']

In [22]:
# add any value to list 
list2=list2+["gene6"]

In [23]:
list2

['gene1', 'gene2', 'gene3', 'gene4', 'gene5', 'gene6']

In [24]:
listx=list1+list2

In [25]:
listx

[1, 2, 3, 4, 5, 'gene1', 'gene2', 'gene3', 'gene4', 'gene5', 'gene6']

In [27]:
# errors with python list 
list_num1=[2.3,4.5,6.5,7.5]
list_num2=[3.3,5.5,1.5,3.5]


In [28]:
list_num3=list_num1*list_num2 # can mulitply by indexing and multiplying every item in the list x=list_num1[0]*list_num2[0]

TypeError: can't multiply sequence by non-int of type 'list'

Base python doesnt have any idea how to multiply the numerical lists, Numpy has a special way to deal with such occurances

# Why arrays why not simple lists 

In [ ]:
# Creating  sample Numpy arrays

In [31]:
nplist_num1=np.array([2.3,4.5,6.5,7.5])
nplist_num2=np.array([3.3,5.5,1.5,3.5])

In [32]:
print(nplist_num1)

[2.3 4.5 6.5 7.5]


check your nplist 2 ?

In [ ]:
Multiplying every item using ....

In [35]:
print(nplist_num1*nplist_num2)

[ 7.59 24.75  9.75 26.25]


# Importing data 

Several was to load data using NumPy

fromfile: fast and efficient loading of binary data (or simple text files)
loadtxt: more flexible way of loading data from a text file
genfromtxt: very flexible data loading, can handle missing/empty data

saving data
save: save an array in a portable format
savetxt: save data to a text file, with custom formatting

Get the data from github repo 

!wget https://github.com/kanekalla/numpy_scipy_workshop2018/blob/master/data/expression_matrix.csv

pythonic way to read in 

In [3]:
with open('data/expression_matrix.csv') as f:
    for row in f:
        print(row)

sample1,sample2,sample3

2255,2390,1947

0,0,0

21,16,14

0,0,1

2,4,1

0,1,1

361,318,387

1782,1781,1807

987,1167,1023

433,494,383

565,599,620

1,1,1

0,0,0

0,0,0

0,0,0

0,0,0

19,23,27

174,166,153

626,587,456



In [ ]:
[click to see data] (https://github.com/kanekalla/numpy_scipy_workshop2018/blob/master/data/expression_matrix.csv)

In [21]:
my_data = np.loadtxt('data/expression_matrix.csv', delimiter=',',skiprows=1)

In [22]:
my_data

array([[2.255e+03, 2.390e+03, 1.947e+03],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [2.100e+01, 1.600e+01, 1.400e+01],
       [0.000e+00, 0.000e+00, 1.000e+00],
       [2.000e+00, 4.000e+00, 1.000e+00],
       [0.000e+00, 1.000e+00, 1.000e+00],
       [3.610e+02, 3.180e+02, 3.870e+02],
       [1.782e+03, 1.781e+03, 1.807e+03],
       [9.870e+02, 1.167e+03, 1.023e+03],
       [4.330e+02, 4.940e+02, 3.830e+02],
       [5.650e+02, 5.990e+02, 6.200e+02],
       [1.000e+00, 1.000e+00, 1.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [1.900e+01, 2.300e+01, 2.700e+01],
       [1.740e+02, 1.660e+02, 1.530e+02],
       [6.260e+02, 5.870e+02, 4.560e+02]])

What is the type of my_data ?

In [23]:
type(my_data)

numpy.ndarray

In [24]:
my_data.dtype

dtype('float64')

In [14]:
my_data_new=np.genfromtxt('data/expression_matrix.csv', skip_header=1, delimiter=",")

In [15]:
my_data_new.dtype

dtype('float64')

In [16]:
my_data_new_no_dtype=np.genfromtxt('data/expression_matrix.csv', skip_header=1, delimiter=",",dtype=None)
my_data_new_no_dtype.dtype

dtype('int64')

In [ ]:
# Accessind arrays

Get the first row in the array 


Note that NumPy arrays use 0-indexing just like other data structures in Python.

In [43]:
my_data[0]

array([2255., 2390., 1947., 2201., 1708., 2095.,  254.])

In [ ]:
Get the 10th row of the array ?

In [48]:
# Accessing elements

# get a single element 
# (here: an element in the first row and column)
print(my_data[0, 0])

2255.0


In [29]:

# get a row 
# (here: 2nd row)
print(my_data[1])

[0. 0. 0.]


In [30]:
# get a column
# (here: 2nd column)
print(my_data[:,1])

[2.390e+03 0.000e+00 1.600e+01 0.000e+00 4.000e+00 1.000e+00 3.180e+02
 1.781e+03 1.167e+03 4.940e+02 5.990e+02 1.000e+00 0.000e+00 0.000e+00
 0.000e+00 0.000e+00 2.300e+01 1.660e+02 5.870e+02]


# Create arrays using NumPy's built in functions

- np.arange: Create an array from a range of numbers
- np.zeros: An array filled with zeroes
- np.ones: An array filled with ones
- np.eye: An identity matrix
- np.random.*: Arrays filled with random values from various distributions

In [ ]:
np.arange(10)

Before using any function, you can always get help from their manuals

In [35]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [38]:
#arange([start,] stop[, step,], dtype=None)
np.arange(1,15,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Using help function create array based on np.zeroes with 2 rows and 3 columns

In [ ]:
hint:

In [39]:
#identity matrix
# np.eye(rows, columns=None, k=0)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
# Setting a random seed for reproducibility
random_state = np.random.RandomState(seed=123)

In [44]:
# Generating a random array
random_matrix = random_state.randint(0, 10, (3, 3)) # a 3 x 3 array
print(random_matrix)

[[2 2 6]
 [1 3 9]
 [6 1 0]]


# Describing an Array

- ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank <br>

- ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim<br>

- ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape<br>

- ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples<br>

- ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize<br>

- ndarray.data

Important attributes in any ndarray are:
    dimensions/axes/rank
    shape
    size

In [46]:
def get_array_attributes(array):
    print("Array ndim: ", array.ndim)
    print("Array shape: ", array.shape)
    print("Array size: ", array.size)
    print()
    
    

In [47]:
get_array_attributes(random_matrix)

Array ndim:  2
Array shape:  (3, 3)
Array size:  9



In [48]:
#check the attributes on the fly
get_array_attributes(np.array([1, 2, 3]))

Array ndim:  1
Array shape:  (3,)
Array size:  3



In [49]:
get_array_attributes(np.array([[1, 2], [3, 4], [5, 6]]))

Array ndim:  2
Array shape:  (3, 2)
Array size:  6



Reshaping arrays after they are created

In [50]:
a = np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.reshape(3, 3) # 2 rows, 3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arithematic operations

Create an array with 2 dimensions, shape of 3*3 and size of 6

In [ ]:
Hints: functions randint(0, 7, (3, 3))

In [59]:
#np.random.randint
array=np.random.randint(0, 7, (3, 3))

In [60]:
array

array([[5, 6, 4],
       [4, 0, 2],
       [3, 6, 2]])

In [64]:
array_1

array([[0, 6, 6],
       [4, 4, 5],
       [4, 4, 5]])

What are the dimensions of this matrix ?

What is the shape of this matrix  ?

What is the size of this matrix ?

What is the data type of this matrix 

In [61]:
# adding 2 to every element the array 
array + 2

array([[7, 8, 6],
       [6, 2, 4],
       [5, 8, 4]])

In [62]:
# multiplying by 2 to every element the array 
array * 2

array([[10, 12,  8],
       [ 8,  0,  4],
       [ 6, 12,  4]])

In [66]:
array_1=np.random.randint(0, 7, (3, 3))
array_1

array([[2, 5, 6],
       [2, 2, 4],
       [0, 2, 4]])

Perform element wise multiplication

In [68]:
array * array_1

array([[10, 30, 24],
       [ 8,  0,  8],
       [ 0, 12,  8]])

In [ ]:
Get the dot product of two matrices

In [69]:
array.dot(array_1)

array([[22, 45, 70],
       [ 8, 24, 32],
       [18, 31, 50]])

In [71]:
#Numpy matrix multiplication fucntion
np.matmul(array,array_1)

array([[22, 45, 70],
       [ 8, 24, 32],
       [18, 31, 50]])

In [ ]:
Numpy Matrices

# Indexing and Slicing

In [81]:
array_index_sort = np.random.randint(0, 20, (6, 6))

In [82]:
array_index_sort

array([[10, 14, 11, 17,  7, 13],
       [ 9,  7,  4,  5,  2,  3],
       [10, 15,  8, 19,  2, 13],
       [ 3, 19, 18, 16,  9, 13],
       [16, 19, 17,  9,  8, 19],
       [ 6, 10, 17,  6, 17,  3]])

In [90]:
# Retrieve element in the first row and first column 
array_index_sort[0,0] # remember the note

10

In [83]:
# Retrieve first row of the array 
array_index_sort[0,]

array([10, 14, 11, 17,  7, 13])

In [84]:
# Retrieve first column of the array 
array_index_sort[:,0]

array([10,  9, 10,  3, 16,  6])

In [85]:
# index based on criteria

In [89]:
array_index_sort[array_index_sort>5]

array([10, 14, 11, 17,  7, 13,  9,  7, 10, 15,  8, 19, 13, 19, 18, 16,  9,
       13, 16, 19, 17,  9,  8, 19,  6, 10, 17,  6, 17])

In [94]:
# conditional logic to change an element 
array_index_sort

array([[10, 14, 11, 17,  7, 13],
       [ 9,  7,  4,  5,  2,  3],
       [10, 15,  8, 19,  2, 13],
       [ 3, 19, 18, 16,  9, 13],
       [16, 19, 17,  9,  8, 19],
       [ 6, 10, 17,  6, 17,  3]])

In [95]:
# conditional logic to change an element 
np.where(array_index_sort<=5,-1,1)

array([[ 1,  1,  1,  1,  1,  1],
       [ 1,  1, -1, -1, -1, -1],
       [ 1,  1,  1,  1, -1,  1],
       [-1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1, -1]])

# Transposition

NumPy's ndarray objects can be easily transposed: rows into columns and vice-versa.

In [101]:
a=np.arange(9).reshape(3,3) # create and reshape it 

In [102]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

# Linear Algebra in Python

In [ ]:
Why linear algebra ?

Scalars, Vectors and Matrices

Matrix is a 2D array of numbers

In [ ]:
# Scalar
scalar = 32

In [ ]:
# Vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([3, 4, 5])

In [12]:
# Matrices
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

# Size of the Matrices
print(A.shape) # (2, 2)
print(B.shape) # (2, 2)

(2, 2)
(2, 2)


Create a new matrix with 3 rows and 4 columns

# Solve linear equation

An algebraic representation of the problem is: A * X = b, where A is square array containing the constant factors, X is a vector of indeterminate values and b are the constrains.

$3x_1+x_2+2x_3=9$ <br>
$x_1+2x_2+x_3=8$ <br>
$2x_2-1x_3=2$ <br>

In [15]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

In [105]:
A = np.array([[3,1,2], [1,2,1], [0,2,-1]])

In [106]:
A

array([[ 3,  1,  2],
       [ 1,  2,  1],
       [ 0,  2, -1]])

In [108]:
b = np.array([9,8,2])

In [109]:
x = np.linalg.solve(A, b)

In [110]:
x

array([0.28571429, 2.42857143, 2.85714286])

In [114]:
round(0.28571429+2* 2.42857143+ 2.85714286)

8

In [ ]:
Eigen Values

define

Eigenvectors find a lot of applications in different domains like computer vision, physics and machine learning. If you have studied machine learning and are familiar with Principal component analysis algorithm, you must know how important the algorithm is when handling a large data set. Have you ever wondered what is going on behind that algorithm? Actually, the concept of Eigenvectors is the backbone of this algorithm. Let us explore Eigen vectors and Eigen values for a better understanding of it.

Eigen values and PCA ...

In [131]:
A = np.array([[3,0], [0,2]])

In [132]:
A

array([[3, 0],
       [0, 2]])

In [137]:
b=np.array([1,3]).reshape(2,1)

In [138]:
b

array([[1],
       [3]])

Multiplying two dimensional vector b to 2*2 matrix A

In [139]:
x=np.matmul(A,b)

In [140]:
x

array([[3],
       [6]])

In [130]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://www.visiondummy.com/wp-content/uploads/2014/03/eigenvectors.png")

Red colored and yellow colored <br> 
This is linear transformation on vector b <br>
Output dimensions are differnet <br>

An eigenvector is a vector whose direction remains unchanged when a linear transformation is applied to it. 

Eigen values are applicable only to square matrix

For a given matrix,vectors whose direction remains unchanged even after applying linear transformation with the matrix are called Eigenvectors

Applications of Eigen vectors: machine learning algorithm Principal Component Analysis.<br>
Suppose you have a data with a large number of features i.e. it has a very high dimensionality eg: 10,000 genes in couple of samples. <br>
Only some features might be useful and others redundant ? <br>
Larger the features, more the disk space and less efficient <br>
PCA identifies tose useful features and discards others <br>
Eigenvectors help PCA to identify these features <br>

In [ ]:
# how to find eigenvectors using Numpy

In [145]:
#create an array
arr = np.arange(1,10).reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
#finding the Eigenvalue and Eigenvectors of arr
np.linalg.eig(arr)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [ ]:
# Getting the shape or reshaping an array

# Generating a random array
rnd = np.random.RandomState(seed=123)
X = rnd.uniform(low=0.0, high=1.0, size=(3, 5))  # a 3 x 5 array

print(X.shape)
print(X.reshape(5, 3))

# SciPy (Scientific Python)
## SciPy sparse matrices

In machine learning tasks, especially those associated with textual analysis, the data may be mostly zeros. Storing all these zeros is very inefficient, and representing in a way that only contains the "non-zero" values can be much more efficient. 

Example: Single cell RNAseq

In [168]:
from scipy import sparse

# Create a random array with a lot of zeros
rnd = np.random.RandomState(seed=123)

X = rnd.uniform(low=0.0, high=1.0, size=(10, 5))
print(X)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]
 [0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029]
 [0.31226122 0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916]
 [0.25045537 0.48303426 0.98555979 0.51948512 0.61289453]]


In [169]:

# set the majority of elements to zero# set t 
X[X < 0.7] = 0
print(X)

[[0.         0.         0.         0.         0.71946897]
 [0.         0.9807642  0.         0.         0.        ]
 [0.         0.72904971 0.         0.         0.        ]
 [0.73799541 0.         0.         0.         0.        ]
 [0.         0.84943179 0.72445532 0.         0.72244338]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.89338916 0.94416002 0.        ]
 [0.         0.         0.         0.         0.86630916]
 [0.         0.         0.98555979 0.         0.        ]]


In [170]:

# turn X into a CSR (Compressed-Sparse-Row) matrix# turn  
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 4)	0.7194689697855631
  (1, 1)	0.9807641983846155
  (2, 1)	0.7290497073840416
  (3, 0)	0.7379954057320357
  (4, 1)	0.8494317940777896
  (4, 2)	0.7244553248606352
  (4, 4)	0.7224433825702216
  (7, 2)	0.8933891631171348
  (7, 3)	0.9441600182038796
  (8, 4)	0.8663091578833659
  (9, 2)	0.985559785610705


In [171]:
# Converting the sparse matrix to a dense array
print(X_csr.toarray())

[[0.         0.         0.         0.         0.71946897]
 [0.         0.9807642  0.         0.         0.        ]
 [0.         0.72904971 0.         0.         0.        ]
 [0.73799541 0.         0.         0.         0.        ]
 [0.         0.84943179 0.72445532 0.         0.72244338]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.89338916 0.94416002 0.        ]
 [0.         0.         0.         0.         0.86630916]
 [0.         0.         0.98555979 0.         0.        ]]


In [172]:
# Create an empty LIL matrix and add some items
X_lil = sparse.lil_matrix((5, 5))

for i, j in np.random.randint(0, 5, (15, 2)):
    X_lil[i, j] = i + j

print(X_lil)
print(type(X_lil))

  (0, 2)	2.0
  (0, 3)	3.0
  (1, 0)	1.0
  (1, 1)	2.0
  (1, 2)	3.0
  (1, 4)	5.0
  (2, 0)	2.0
  (2, 2)	4.0
  (3, 1)	4.0
  (3, 2)	5.0
  (3, 4)	7.0
  (4, 0)	4.0
  (4, 2)	6.0
<class 'scipy.sparse.lil.lil_matrix'>


In [174]:
X_dense = X_lil.toarray()
print(X_dense)
print(type(X_dense))

[[0. 0. 2. 3. 0.]
 [1. 2. 3. 0. 5.]
 [2. 0. 4. 0. 0.]
 [0. 4. 5. 0. 7.]
 [4. 0. 6. 0. 0.]]
<class 'numpy.ndarray'>


In [177]:
X_csr  =  X_lil.tocsr()
print((X_csr))
print((type((X_csr))))

  (0, 2)	2.0
  (0, 3)	3.0
  (1, 0)	1.0
  (1, 1)	2.0
  (1, 2)	3.0
  (1, 4)	5.0
  (2, 0)	2.0
  (2, 2)	4.0
  (3, 1)	4.0
  (3, 2)	5.0
  (3, 4)	7.0
  (4, 0)	4.0
  (4, 2)	6.0
<class 'scipy.sparse.csr.csr_matrix'>



The available sparse formats that can be useful for various problems:

CSR (compressed sparse row) <br>
CSC (compressed sparse column) <br>
BSR (block sparse row) <br>
COO (coordinate) <br>
DIA (diagonal) <br>
DOK (dictionary of keys) <br>
LIL (list in list) <br>

In [ ]:
Excercises

1. Create a random vector of length 10 and reshape to a matrix of shape 2*5 

2. Create a 5x5 matrix with row values ranging from 0 to 4

3. read the file expression_matrix.csv as exp_array and find the maximum, miimum values of the matrix 

4. get the sumary statistics of the array a taking values from np.arange(10) using scipy stats module

5.  How to get the dates of yesterday, today and tomorrow?

References: <br>
   1. http://www.numpy.org/ <br>
   2. https://www.scipy.org/<br>
   3. http://cs231n.github.io/python-numpy-tutorial/#numpy <br>
   4.  http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html <br>
   5.  https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb <br>
        