# Python: Numpy/scipy

#Things you will learn in this workshop
Data structures in Python
Introduction to Numpy and Scipy packages
Create and manipulate multidimensional Numpy arrays
Import data and manipulate it
Use SciPy’s basic statistical functions


# Numpy (Numerical Python)

-> a powerful N-dimensional array object
-> sophisticated (broadcasting) functions
-> tools for integrating C/C++ and Fortran code
-> useful linear algebra, Fourier transform, and random number capabilities

Before we understand these statements from Numpy page we will go to the basic data storage in Pyhton (Data structures)
Four built-in data structures in Python - list, tuple, dictionary and set
Arrays is like lists but a lot different from lists which we will see 


List:
    
    A list is a data structure that holds an ordered collection of items.
    List is a most versatile datatype which can be written as a list of items(comma sep values) between square brackets.
    Important thing about a list is that items in a list need not be of the same type.

In [10]:
list1=[1,2,3,4,5]
list2=["gene1","gene2","gene3","gene4"]

# Accessing Values in Lists

In [6]:
print("My first value in list1 is :",list1[0]) # does strat from 0

My first calue in mylist is : 1


In [9]:
print("My first value in list2 is :",list2[0])

My first value in genelist_1 is : gene1


NumPy array is a central data structure of the numpy library.
NumPy’s main object is the homogeneous multidimensional array.
It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes.
NumPy’s array class is called "ndarray"
The number of dimensions is the rank of the array;
the shape of an array is a tuple of integers giving the size of the array along each dimension.


In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Array

ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank

#ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim

#ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape

#ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples

#ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize

#ndarray.data

In [ ]:
Important attributes in any ndarray are:
    dimensions
    shape
    size
    dtype
    itemsize

In [13]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [14]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [16]:
b # should the columns be 0 and 1 ?

array([[2, 3],
       [6, 7]])

Integer array indexing:
           When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [ ]:
# start from here 

References:
    http://www.numpy.org/
    http://cs231n.github.io/python-numpy-tutorial/#numpy
    
        