# Python: Numpy/scipy

- Things you will learn in this workshop <br>
- Introduction to Data structures in Python & Numpy <br>
- Iroduction to Numpy and Scipy packages <br>
- Create and manipulate multi-dimensional arrays in Numpy <br>
- Import and manipulate data<br>
- SciPy’s basic statistical functions<br>


# Reproducibility

In [ ]:
Which Python version am I using ?

In [22]:
import sys
print(sys.version)

3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]


In [ ]:
import numpy as np
import matplotlib as plt
import seaborn as sns

In [ ]:
print(np.__version__)

My Matplotlib version is :

In [ ]:
print(plt.__version__)

Scientific computing in Python builds upon a small core of packages:


NumPy, the fundamental package for numerical computation. It defines the numerical array and matrix types and basic operations on them.

The SciPy library, a collection of numerical algorithms and domain-specific toolboxes, including signal processing, optimization, statistics and much more.

# Numpy (Numerical Python)

-> a powerful N-dimensional array object <br>
-> tools for integrating C/C++ and Fortran code <br>
-> sophisticated (broadcasting) functions <br>
-> useful linear algebra, Fourier transform, and random number capabilities <br>
-> Efficient multi-dimensional container for generic data & seamless integration with arbitraty data types <br>

Before we understand these statements from Numpy page we will go to the basic data storage in Pyhton (Data structures)
Four built-in data structures in Python - list, tuple, dictionary and set
Arrays is like lists but a lot different from lists which we will see 


List:
    
    A list is a data structure that holds an ordered collection of items.
    List is a most versatile datatype which can be written as a list of items(comma sep values) between square brackets.
    Important thing about a list is that items in a list need not be of the same type.

Numpy provides many functions to create arrays
Numpy offers several ways to index into arrays.
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

Datatypes:
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print x.dtype, y.dtype, z.dtype

In [17]:
list1=[1,2,3,4,5]
list2=["gene1","gene2","gene3","gene4"] # can hold different types of data # Add or remove the data

# Accessing Values in Lists

In [18]:
print("My first value in list1 is :",list1[0]) # does strat from 0

My first value in list1 is : 1


In [19]:
print("My first value in list2 is :",list2[0])

My first value in list2 is : gene1


NumPy array is a central data structure of the numpy library.
NumPy’s main object is the homogeneous multidimensional array.
It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes.
NumPy’s array class is called "ndarray"
The number of dimensions is the rank of the array;
the shape of an array is a tuple of integers giving the size of the array along each dimension.


In [20]:
#add any values using built in function "append"
#Add an item to the end of the list
list2.append('gene5')

In [21]:
list2

['gene1', 'gene2', 'gene3', 'gene4', 'gene5']

In [22]:
# add any value to list 
list2=list2+["gene6"]

In [23]:
list2

['gene1', 'gene2', 'gene3', 'gene4', 'gene5', 'gene6']

In [24]:
listx=list1+list2

In [25]:
listx

[1, 2, 3, 4, 5, 'gene1', 'gene2', 'gene3', 'gene4', 'gene5', 'gene6']

In [26]:
# errors with python list 
list_num1=[2.3,4.,6.5,7.5]
list_num2=[3.3,5.,1.5,3.5]


In [27]:
list_num3=list_num1*list_num2 # can mulitply by indexing and multiplying every item in the list x=list_num1[0]*list_num2[0]

TypeError: can't multiply sequence by non-int of type 'list'

Base python doesnt have any idea how to multiply the numerical lists, Numpy has a special way to deal with such occurances

1.14.5


In [15]:
# How do I get these versions

My matplotlib pyplot is from 

2.2.2


In [18]:
print(sns.__version__)

0.8.1


SyntaxError: invalid syntax (<ipython-input-19-1663cd30cb7c>, line 1)

In [31]:
nplist_num1=np.array([2.3,4.5,6.5,7.5])
nplist_num2=np.array([3.3,5.5,1.5,3.5])

In [32]:
print(nplist_num1)

[2.3 4.5 6.5 7.5]


In [33]:
print(nplist_num2)

[3.3 5.5 1.5 3.5]


In [35]:
print(nplist_num1*nplist_num2)

[ 7.59 24.75  9.75 26.25]


Array

ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank

#ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim

#ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape

#ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples

#ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize

#ndarray.data

In [ ]:
Important attributes in any ndarray are:
    dimensions
    shape
    size
    dtype
    itemsize

In [ ]:
#The way Numpy handles the arrays 

In [2]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
print (a.dtype)

int64


In [15]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [16]:
b # should the columns be 0 and 1 ?

array([[2, 3],
       [6, 7]])

Integer array indexing:
           When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [ ]:
# start from here 

References:
    http://www.numpy.org/ <br>
    http://cs231n.github.io/python-numpy-tutorial/#numpy <br>
    http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html <br>
    
        